# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cars.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cars.proto',
  package='userGrpc',
  syntax='proto3',
  serialized_options=b'\n\031io.grpc.examples.userGrpcB\010GrpcUserP\001\242\002\003RTG',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ncars.proto\x12\x08userGrpc\"3\n\x08UserData\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\t\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xdc\x01\n\x04User\x12\x33\n\x07\x41\x64\x64User\x12\x12.userGrpc.UserData\x1a\x12.userGrpc.UserData\"\x00\x12\x36\n\nUpdateUser\x12\x12.userGrpc.UserData\x1a\x12.userGrpc.UserData\"\x00\x12\x31\n\x07GetUser\x12\x10.userGrpc.UserID\x1a\x12.userGrpc.UserData\"\x00\x12\x34\n\nRemoveUser\x12\x10.userGrpc.UserID\x1a\x12.userGrpc.UserData\"\x00\x42-\n\x19io.grpc.examples.userGrpcB\x08GrpcUserP\x01\xa2\x02\x03RTGb\x06proto3'
)




_USERDATA = _descriptor.Descriptor(
  name='UserData',
  full_name='userGrpc.UserData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='userGrpc.UserData.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='userGrpc.UserData.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='userGrpc.UserData.price', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=75,
)


_USERID = _descriptor.Descriptor(
  name='UserID',
  full_name='userGrpc.UserID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='userGrpc.UserID.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['UserData'] = _USERDATA
DESCRIPTOR.message_types_by_name['UserID'] = _USERID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserData = _reflection.GeneratedProtocolMessageType('UserData', (_message.Message,), {
  'DESCRIPTOR' : _USERDATA,
  '__module__' : 'cars_pb2'
  # @@protoc_insertion_point(class_scope:userGrpc.UserData)
  })
_sym_db.RegisterMessage(UserData)

UserID = _reflection.GeneratedProtocolMessageType('UserID', (_message.Message,), {
  'DESCRIPTOR' : _USERID,
  '__module__' : 'cars_pb2'
  # @@protoc_insertion_point(class_scope:userGrpc.UserID)
  })
_sym_db.RegisterMessage(UserID)


DESCRIPTOR._options = None

_USER = _descriptor.ServiceDescriptor(
  name='User',
  full_name='userGrpc.User',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=100,
  serialized_end=320,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddUser',
    full_name='userGrpc.User.AddUser',
    index=0,
    containing_service=None,
    input_type=_USERDATA,
    output_type=_USERDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateUser',
    full_name='userGrpc.User.UpdateUser',
    index=1,
    containing_service=None,
    input_type=_USERDATA,
    output_type=_USERDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetUser',
    full_name='userGrpc.User.GetUser',
    index=2,
    containing_service=None,
    input_type=_USERID,
    output_type=_USERDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveUser',
    full_name='userGrpc.User.RemoveUser',
    index=3,
    containing_service=None,
    input_type=_USERID,
    output_type=_USERDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['User'] = _USER

# @@protoc_insertion_point(module_scope)
